CLASS ycl_dmo_city_query DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
   INTERFACES : if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ycl_dmo_city_query IMPLEMENTATION.
  METHOD if_oo_adt_classrun~main.
    DELETE from YDMO_PARTNER_DB.
    delete from YDMO_DPARTNER_DB.
  ENDMETHOD.

ENDCLASS.
